### ISSUE TITLE
Vise den offentlige forsiden som et slideshow

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#220]
Scrolle ned seksjon for seksjon og vise alle bildene.

Ment til bruk på info-skjerm.

Visningen starter etter 10 sekunder og stopper ved brukerinteraksjon på siden.

**Comment by donv** [comment]
Da har jeg lagt ut denne.  @AtleTollefsen  @Atle-Tollefsen Hva synes du?  Kan brukes på info-skjerm?

**Comment by AtleTollefsen** [comment]
Fikk opp et blokk med ingen data, men hva tenkte du på å legge ut?'


Atle Tollefsen
Service Delivery Owner
Service Management Office Cluster North


Securitas AS
PB. 100, Alnabru,
0614 OSLO
Norway
Visiting address: Bøkkerveien 5, 0579 OSLO, Norway

Mobile Phone: +4741295454
Switchboard: 02452 or +47 22 57 73 08
Email: ***@***.******@***.***>


***@***.***

Disclaimer: The contents of this e-mail message (including any attachments hereto) are confidential to and for the use of the recipient to whom it is addressed only. If you receive this transmission in error, please notify the sender of this immediately and delete the message from your system. Any distribution, reproduction or use of this message by someone other than recipient is not authorized and may be unlawful.
P Please consider the environment before printing this e-mail.




From: Uwe Kubosch ***@***.***>
Sent: fredag 26. november 2021 00:26
To: Romerike-Jujutsu-Klubb/rjjk_web ***@***.***>
Cc: Atle Tollefsen ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Romerike-Jujutsu-Klubb/rjjk_web] Vise den offentlige forsiden som et slideshow (Issue #220)


Da har jeg lagt ut denne. @AtleTollefsen<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAtleTollefsen&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872198819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0FTMTDaDiYc1wHzTqNYBVsaH56gXX9UKrMS3B0fv2Cs%3D&reserved=0> @Atle-Tollefsen<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAtle-Tollefsen&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872198819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NK2PnyiS8hgozy12FNlMl6KOyStNTOQtswD3CFKZkcw%3D&reserved=0> Hva synes du? Kan brukes på info-skjerm?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRomerike-Jujutsu-Klubb%2Frjjk_web%2Fissues%2F220%23issuecomment-979513716&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872208776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FroOHBN7Do8mdX6Olwmeg0jnHqlLxRRWPobkw6vN4oM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL2GO3LTFJI4EDE2R2XFG33UN3AZ7ANCNFSM5IZL644Q&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872208776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UMKddCNUU4dty%2FQkgiAoxYgzDdNY80Vx6XoMa0Z1wC8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872218732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F7b7ukPzzIM9PH26jcLxTUoiQOj7oNP4r5U9egLLaj8%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Catle.tollefsen%40securitas.no%7C12118ca486cf4bea2c1808d9b06aff6d%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637734795872218732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4v1TEsC4ycqiQ9bypJO1TAkReypGHW3MvYrr3NKouUM%3D&reserved=0>.

**Comment by donv** [comment]
Jeg har lagt ut videoen du lagde på forsiden, med automatisk avspilling og visning av siden:

    https://www.jujutsu.no/

eller hvis du er logget på:

    https://www.jujutsu.no/welcome/front_parallax

Ser det greit ut?
